/**
 * generated by Xtext 2.29.0
 */
package org.xtext.ui23.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input Text</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.ui23.dsl.DslPackage#getInputText()
 * @model
 * @generated
 */
public interface InputText extends Element, CrossRef
{
} // InputText
