/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Other Relation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.OtherRelation#isSingleto <em>Singleto</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.OtherRelation#isManyto <em>Manyto</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.OtherRelation#getFrom <em>From</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.OtherRelation#getTo <em>To</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOtherRelation()
 * @model
 * @generated
 */
public interface OtherRelation extends Relation
{
  /**
   * Returns the value of the '<em><b>Singleto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Singleto</em>' attribute.
   * @see #setSingleto(boolean)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOtherRelation_Singleto()
   * @model
   * @generated
   */
  boolean isSingleto();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.OtherRelation#isSingleto <em>Singleto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Singleto</em>' attribute.
   * @see #isSingleto()
   * @generated
   */
  void setSingleto(boolean value);

  /**
   * Returns the value of the '<em><b>Manyto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Manyto</em>' attribute.
   * @see #setManyto(boolean)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOtherRelation_Manyto()
   * @model
   * @generated
   */
  boolean isManyto();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.OtherRelation#isManyto <em>Manyto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Manyto</em>' attribute.
   * @see #isManyto()
   * @generated
   */
  void setManyto(boolean value);

  /**
   * Returns the value of the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' reference.
   * @see #setFrom(Entity)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOtherRelation_From()
   * @model
   * @generated
   */
  Entity getFrom();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.OtherRelation#getFrom <em>From</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' reference.
   * @see #getFrom()
   * @generated
   */
  void setFrom(Entity value);

  /**
   * Returns the value of the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' reference.
   * @see #setTo(Entity)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOtherRelation_To()
   * @model
   * @generated
   */
  Entity getTo();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.OtherRelation#getTo <em>To</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' reference.
   * @see #getTo()
   * @generated
   */
  void setTo(Entity value);

} // OtherRelation
