/**
 * generated by Xtext 2.29.0
 */
package org.xtext.exam22.dsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.exam22.dsl.DslFactory
 * @model kind="package"
 * @generated
 */
public interface DslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/exam22/Dsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DslPackage eINSTANCE = org.xtext.exam22.dsl.impl.DslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.ModelImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Functions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__FUNCTIONS = 1;

  /**
   * The feature id for the '<em><b>Scenarios</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__SCENARIOS = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.CrossRefImpl <em>Cross Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.CrossRefImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getCrossRef()
   * @generated
   */
  int CROSS_REF = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CROSS_REF__NAME = 0;

  /**
   * The number of structural features of the '<em>Cross Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CROSS_REF_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.FunctionImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__NAME = CROSS_REF__NAME;

  /**
   * The feature id for the '<em><b>Types</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__TYPES = CROSS_REF_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Return Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__RETURN_TYPE = CROSS_REF_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = CROSS_REF_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.ScenarioImpl <em>Scenario</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.ScenarioImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getScenario()
   * @generated
   */
  int SCENARIO = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__NAME = CROSS_REF__NAME;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__PARAMETERS = CROSS_REF_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__VARIABLES = CROSS_REF_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__STATEMENTS = CROSS_REF_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Scenario</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO_FEATURE_COUNT = CROSS_REF_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.StatementImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__NAME = CROSS_REF__NAME;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__EXPRESSION = CROSS_REF_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = CROSS_REF_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.VariableDefImpl <em>Variable Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.VariableDefImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getVariableDef()
   * @generated
   */
  int VARIABLE_DEF = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DEF__NAME = CROSS_REF__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DEF__TYPE = CROSS_REF_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DEF_FEATURE_COUNT = CROSS_REF_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.AnnounceImpl <em>Announce</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.AnnounceImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getAnnounce()
   * @generated
   */
  int ANNOUNCE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOUNCE__NAME = STATEMENT__NAME;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOUNCE__EXPRESSION = STATEMENT__EXPRESSION;

  /**
   * The feature id for the '<em><b>Targets</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOUNCE__TARGETS = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Announce</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOUNCE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.QuestionImpl <em>Question</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.QuestionImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getQuestion()
   * @generated
   */
  int QUESTION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__NAME = STATEMENT__NAME;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__EXPRESSION = STATEMENT__EXPRESSION;

  /**
   * The feature id for the '<em><b>Output</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__OUTPUT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__VARIABLE = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Targets</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__TARGETS = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Question</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.EndImpl <em>End</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.EndImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getEnd()
   * @generated
   */
  int END = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END__NAME = STATEMENT__NAME;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END__EXPRESSION = STATEMENT__EXPRESSION;

  /**
   * The number of structural features of the '<em>End</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.TargetImpl <em>Target</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.TargetImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getTarget()
   * @generated
   */
  int TARGET = 8;

  /**
   * The feature id for the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET__TO = 0;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET__EXPRESSIONS = 1;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET__CONDITION = 2;

  /**
   * The feature id for the '<em><b>Ending Targets</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET__ENDING_TARGETS = 3;

  /**
   * The number of structural features of the '<em>Target</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.EndingTargetImpl <em>Ending Target</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.EndingTargetImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getEndingTarget()
   * @generated
   */
  int ENDING_TARGET = 9;

  /**
   * The feature id for the '<em><b>End</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENDING_TARGET__END = 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENDING_TARGET__TARGET = 1;

  /**
   * The number of structural features of the '<em>Ending Target</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENDING_TARGET_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.ParameterImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__NAME = CROSS_REF__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__TYPE = CROSS_REF_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = CROSS_REF_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.ExpImpl <em>Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.ExpImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getExp()
   * @generated
   */
  int EXP = 11;

  /**
   * The number of structural features of the '<em>Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.BooleanImpl <em>Boolean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.BooleanImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getBoolean()
   * @generated
   */
  int BOOLEAN = 13;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN__LEFT = EXP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN__OP = EXP_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN__RIGHT = EXP_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Boolean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_FEATURE_COUNT = EXP_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.EqualImpl <em>Equal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.EqualImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getEqual()
   * @generated
   */
  int EQUAL = 14;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL__LEFT = EXP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL__OP = EXP_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL__RIGHT = EXP_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Equal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL_FEATURE_COUNT = EXP_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.CompareImpl <em>Compare</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.CompareImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getCompare()
   * @generated
   */
  int COMPARE = 15;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARE__LEFT = EXP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARE__OP = EXP_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARE__RIGHT = EXP_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Compare</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARE_FEATURE_COUNT = EXP_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.ConcatImpl <em>Concat</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.ConcatImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getConcat()
   * @generated
   */
  int CONCAT = 16;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCAT__LEFT = EXP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCAT__RIGHT = EXP_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Concat</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCAT_FEATURE_COUNT = EXP_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.PlusMinusImpl <em>Plus Minus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.PlusMinusImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getPlusMinus()
   * @generated
   */
  int PLUS_MINUS = 17;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_MINUS__LEFT = EXP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_MINUS__OP = EXP_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_MINUS__RIGHT = EXP_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Plus Minus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_MINUS_FEATURE_COUNT = EXP_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.MultDivImpl <em>Mult Div</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.MultDivImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getMultDiv()
   * @generated
   */
  int MULT_DIV = 18;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT_DIV__LEFT = EXP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT_DIV__OP = EXP_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT_DIV__RIGHT = EXP_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Mult Div</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT_DIV_FEATURE_COUNT = EXP_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.IntConstantImpl <em>Int Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.IntConstantImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getIntConstant()
   * @generated
   */
  int INT_CONSTANT = 19;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_CONSTANT__VALUE = EXP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_CONSTANT_FEATURE_COUNT = EXP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.StringConstantImpl <em>String Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.StringConstantImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getStringConstant()
   * @generated
   */
  int STRING_CONSTANT = 20;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_CONSTANT__VALUE = EXP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_CONSTANT_FEATURE_COUNT = EXP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.BoolConstantImpl <em>Bool Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.BoolConstantImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getBoolConstant()
   * @generated
   */
  int BOOL_CONSTANT = 21;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_CONSTANT__VALUE = EXP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Bool Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_CONSTANT_FEATURE_COUNT = EXP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.NotImpl <em>Not</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.NotImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getNot()
   * @generated
   */
  int NOT = 22;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT__EXP = EXP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Not</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_FEATURE_COUNT = EXP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.TypeConstantImpl <em>Type Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.TypeConstantImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getTypeConstant()
   * @generated
   */
  int TYPE_CONSTANT = 23;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_CONSTANT__TYPE = EXP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Type Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_CONSTANT_FEATURE_COUNT = EXP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.ThisImpl <em>This</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.ThisImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getThis()
   * @generated
   */
  int THIS = 24;

  /**
   * The number of structural features of the '<em>This</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THIS_FEATURE_COUNT = EXP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.VarRefImpl <em>Var Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.VarRefImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getVarRef()
   * @generated
   */
  int VAR_REF = 25;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_REF__REF = EXP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Var Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_REF_FEATURE_COUNT = EXP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.FuncCallImpl <em>Func Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.FuncCallImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getFuncCall()
   * @generated
   */
  int FUNC_CALL = 26;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNC_CALL__REF = EXP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNC_CALL__EXPRESSIONS = EXP_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Func Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNC_CALL_FEATURE_COUNT = EXP_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.exam22.dsl.impl.ParenthesisImpl <em>Parenthesis</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.exam22.dsl.impl.ParenthesisImpl
   * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getParenthesis()
   * @generated
   */
  int PARENTHESIS = 27;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTHESIS__EXP = EXP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Parenthesis</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTHESIS_FEATURE_COUNT = EXP_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.exam22.dsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.exam22.dsl.Model#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.exam22.dsl.Model#getName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.exam22.dsl.Model#getFunctions <em>Functions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Functions</em>'.
   * @see org.xtext.exam22.dsl.Model#getFunctions()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Functions();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.exam22.dsl.Model#getScenarios <em>Scenarios</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Scenarios</em>'.
   * @see org.xtext.exam22.dsl.Model#getScenarios()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Scenarios();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see org.xtext.exam22.dsl.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.exam22.dsl.Function#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Types</em>'.
   * @see org.xtext.exam22.dsl.Function#getTypes()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Types();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.exam22.dsl.Function#getReturnType <em>Return Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Return Type</em>'.
   * @see org.xtext.exam22.dsl.Function#getReturnType()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_ReturnType();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.Scenario <em>Scenario</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scenario</em>'.
   * @see org.xtext.exam22.dsl.Scenario
   * @generated
   */
  EClass getScenario();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.exam22.dsl.Scenario#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see org.xtext.exam22.dsl.Scenario#getParameters()
   * @see #getScenario()
   * @generated
   */
  EReference getScenario_Parameters();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.exam22.dsl.Scenario#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variables</em>'.
   * @see org.xtext.exam22.dsl.Scenario#getVariables()
   * @see #getScenario()
   * @generated
   */
  EReference getScenario_Variables();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.exam22.dsl.Scenario#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.xtext.exam22.dsl.Scenario#getStatements()
   * @see #getScenario()
   * @generated
   */
  EReference getScenario_Statements();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see org.xtext.exam22.dsl.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.exam22.dsl.Statement#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see org.xtext.exam22.dsl.Statement#getExpression()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Expression();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.VariableDef <em>Variable Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Def</em>'.
   * @see org.xtext.exam22.dsl.VariableDef
   * @generated
   */
  EClass getVariableDef();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.exam22.dsl.VariableDef#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.exam22.dsl.VariableDef#getType()
   * @see #getVariableDef()
   * @generated
   */
  EAttribute getVariableDef_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.Announce <em>Announce</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Announce</em>'.
   * @see org.xtext.exam22.dsl.Announce
   * @generated
   */
  EClass getAnnounce();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.exam22.dsl.Announce#getTargets <em>Targets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Targets</em>'.
   * @see org.xtext.exam22.dsl.Announce#getTargets()
   * @see #getAnnounce()
   * @generated
   */
  EReference getAnnounce_Targets();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.Question <em>Question</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Question</em>'.
   * @see org.xtext.exam22.dsl.Question
   * @generated
   */
  EClass getQuestion();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.exam22.dsl.Question#getOutput <em>Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Output</em>'.
   * @see org.xtext.exam22.dsl.Question#getOutput()
   * @see #getQuestion()
   * @generated
   */
  EReference getQuestion_Output();

  /**
   * Returns the meta object for the reference '{@link org.xtext.exam22.dsl.Question#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variable</em>'.
   * @see org.xtext.exam22.dsl.Question#getVariable()
   * @see #getQuestion()
   * @generated
   */
  EReference getQuestion_Variable();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.exam22.dsl.Question#getTargets <em>Targets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Targets</em>'.
   * @see org.xtext.exam22.dsl.Question#getTargets()
   * @see #getQuestion()
   * @generated
   */
  EReference getQuestion_Targets();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.End <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>End</em>'.
   * @see org.xtext.exam22.dsl.End
   * @generated
   */
  EClass getEnd();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.Target <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Target</em>'.
   * @see org.xtext.exam22.dsl.Target
   * @generated
   */
  EClass getTarget();

  /**
   * Returns the meta object for the reference '{@link org.xtext.exam22.dsl.Target#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>To</em>'.
   * @see org.xtext.exam22.dsl.Target#getTo()
   * @see #getTarget()
   * @generated
   */
  EReference getTarget_To();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.exam22.dsl.Target#getExpressions <em>Expressions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expressions</em>'.
   * @see org.xtext.exam22.dsl.Target#getExpressions()
   * @see #getTarget()
   * @generated
   */
  EReference getTarget_Expressions();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.exam22.dsl.Target#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see org.xtext.exam22.dsl.Target#getCondition()
   * @see #getTarget()
   * @generated
   */
  EReference getTarget_Condition();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.exam22.dsl.Target#getEndingTargets <em>Ending Targets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ending Targets</em>'.
   * @see org.xtext.exam22.dsl.Target#getEndingTargets()
   * @see #getTarget()
   * @generated
   */
  EReference getTarget_EndingTargets();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.EndingTarget <em>Ending Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ending Target</em>'.
   * @see org.xtext.exam22.dsl.EndingTarget
   * @generated
   */
  EClass getEndingTarget();

  /**
   * Returns the meta object for the reference '{@link org.xtext.exam22.dsl.EndingTarget#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>End</em>'.
   * @see org.xtext.exam22.dsl.EndingTarget#getEnd()
   * @see #getEndingTarget()
   * @generated
   */
  EReference getEndingTarget_End();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.exam22.dsl.EndingTarget#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Target</em>'.
   * @see org.xtext.exam22.dsl.EndingTarget#getTarget()
   * @see #getEndingTarget()
   * @generated
   */
  EReference getEndingTarget_Target();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see org.xtext.exam22.dsl.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.exam22.dsl.Parameter#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.exam22.dsl.Parameter#getType()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.Exp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exp</em>'.
   * @see org.xtext.exam22.dsl.Exp
   * @generated
   */
  EClass getExp();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.CrossRef <em>Cross Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cross Ref</em>'.
   * @see org.xtext.exam22.dsl.CrossRef
   * @generated
   */
  EClass getCrossRef();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.exam22.dsl.CrossRef#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.exam22.dsl.CrossRef#getName()
   * @see #getCrossRef()
   * @generated
   */
  EAttribute getCrossRef_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.Boolean <em>Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean</em>'.
   * @see org.xtext.exam22.dsl.Boolean
   * @generated
   */
  EClass getBoolean();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.exam22.dsl.Boolean#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.exam22.dsl.Boolean#getLeft()
   * @see #getBoolean()
   * @generated
   */
  EReference getBoolean_Left();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.exam22.dsl.Boolean#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see org.xtext.exam22.dsl.Boolean#getOp()
   * @see #getBoolean()
   * @generated
   */
  EAttribute getBoolean_Op();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.exam22.dsl.Boolean#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.exam22.dsl.Boolean#getRight()
   * @see #getBoolean()
   * @generated
   */
  EReference getBoolean_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.Equal <em>Equal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equal</em>'.
   * @see org.xtext.exam22.dsl.Equal
   * @generated
   */
  EClass getEqual();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.exam22.dsl.Equal#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.exam22.dsl.Equal#getLeft()
   * @see #getEqual()
   * @generated
   */
  EReference getEqual_Left();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.exam22.dsl.Equal#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see org.xtext.exam22.dsl.Equal#getOp()
   * @see #getEqual()
   * @generated
   */
  EAttribute getEqual_Op();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.exam22.dsl.Equal#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.exam22.dsl.Equal#getRight()
   * @see #getEqual()
   * @generated
   */
  EReference getEqual_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.Compare <em>Compare</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Compare</em>'.
   * @see org.xtext.exam22.dsl.Compare
   * @generated
   */
  EClass getCompare();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.exam22.dsl.Compare#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.exam22.dsl.Compare#getLeft()
   * @see #getCompare()
   * @generated
   */
  EReference getCompare_Left();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.exam22.dsl.Compare#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see org.xtext.exam22.dsl.Compare#getOp()
   * @see #getCompare()
   * @generated
   */
  EAttribute getCompare_Op();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.exam22.dsl.Compare#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.exam22.dsl.Compare#getRight()
   * @see #getCompare()
   * @generated
   */
  EReference getCompare_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.Concat <em>Concat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Concat</em>'.
   * @see org.xtext.exam22.dsl.Concat
   * @generated
   */
  EClass getConcat();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.exam22.dsl.Concat#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.exam22.dsl.Concat#getLeft()
   * @see #getConcat()
   * @generated
   */
  EReference getConcat_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.exam22.dsl.Concat#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.exam22.dsl.Concat#getRight()
   * @see #getConcat()
   * @generated
   */
  EReference getConcat_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.PlusMinus <em>Plus Minus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Plus Minus</em>'.
   * @see org.xtext.exam22.dsl.PlusMinus
   * @generated
   */
  EClass getPlusMinus();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.exam22.dsl.PlusMinus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.exam22.dsl.PlusMinus#getLeft()
   * @see #getPlusMinus()
   * @generated
   */
  EReference getPlusMinus_Left();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.exam22.dsl.PlusMinus#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see org.xtext.exam22.dsl.PlusMinus#getOp()
   * @see #getPlusMinus()
   * @generated
   */
  EAttribute getPlusMinus_Op();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.exam22.dsl.PlusMinus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.exam22.dsl.PlusMinus#getRight()
   * @see #getPlusMinus()
   * @generated
   */
  EReference getPlusMinus_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.MultDiv <em>Mult Div</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mult Div</em>'.
   * @see org.xtext.exam22.dsl.MultDiv
   * @generated
   */
  EClass getMultDiv();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.exam22.dsl.MultDiv#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.exam22.dsl.MultDiv#getLeft()
   * @see #getMultDiv()
   * @generated
   */
  EReference getMultDiv_Left();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.exam22.dsl.MultDiv#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see org.xtext.exam22.dsl.MultDiv#getOp()
   * @see #getMultDiv()
   * @generated
   */
  EAttribute getMultDiv_Op();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.exam22.dsl.MultDiv#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.exam22.dsl.MultDiv#getRight()
   * @see #getMultDiv()
   * @generated
   */
  EReference getMultDiv_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.IntConstant <em>Int Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Constant</em>'.
   * @see org.xtext.exam22.dsl.IntConstant
   * @generated
   */
  EClass getIntConstant();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.exam22.dsl.IntConstant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.exam22.dsl.IntConstant#getValue()
   * @see #getIntConstant()
   * @generated
   */
  EAttribute getIntConstant_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.StringConstant <em>String Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Constant</em>'.
   * @see org.xtext.exam22.dsl.StringConstant
   * @generated
   */
  EClass getStringConstant();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.exam22.dsl.StringConstant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.exam22.dsl.StringConstant#getValue()
   * @see #getStringConstant()
   * @generated
   */
  EAttribute getStringConstant_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.BoolConstant <em>Bool Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool Constant</em>'.
   * @see org.xtext.exam22.dsl.BoolConstant
   * @generated
   */
  EClass getBoolConstant();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.exam22.dsl.BoolConstant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.exam22.dsl.BoolConstant#getValue()
   * @see #getBoolConstant()
   * @generated
   */
  EAttribute getBoolConstant_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.Not <em>Not</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Not</em>'.
   * @see org.xtext.exam22.dsl.Not
   * @generated
   */
  EClass getNot();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.exam22.dsl.Not#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see org.xtext.exam22.dsl.Not#getExp()
   * @see #getNot()
   * @generated
   */
  EReference getNot_Exp();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.TypeConstant <em>Type Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type Constant</em>'.
   * @see org.xtext.exam22.dsl.TypeConstant
   * @generated
   */
  EClass getTypeConstant();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.exam22.dsl.TypeConstant#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.exam22.dsl.TypeConstant#getType()
   * @see #getTypeConstant()
   * @generated
   */
  EAttribute getTypeConstant_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.This <em>This</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>This</em>'.
   * @see org.xtext.exam22.dsl.This
   * @generated
   */
  EClass getThis();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.VarRef <em>Var Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Ref</em>'.
   * @see org.xtext.exam22.dsl.VarRef
   * @generated
   */
  EClass getVarRef();

  /**
   * Returns the meta object for the reference '{@link org.xtext.exam22.dsl.VarRef#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see org.xtext.exam22.dsl.VarRef#getRef()
   * @see #getVarRef()
   * @generated
   */
  EReference getVarRef_Ref();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.FuncCall <em>Func Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Func Call</em>'.
   * @see org.xtext.exam22.dsl.FuncCall
   * @generated
   */
  EClass getFuncCall();

  /**
   * Returns the meta object for the reference '{@link org.xtext.exam22.dsl.FuncCall#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see org.xtext.exam22.dsl.FuncCall#getRef()
   * @see #getFuncCall()
   * @generated
   */
  EReference getFuncCall_Ref();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.exam22.dsl.FuncCall#getExpressions <em>Expressions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expressions</em>'.
   * @see org.xtext.exam22.dsl.FuncCall#getExpressions()
   * @see #getFuncCall()
   * @generated
   */
  EReference getFuncCall_Expressions();

  /**
   * Returns the meta object for class '{@link org.xtext.exam22.dsl.Parenthesis <em>Parenthesis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parenthesis</em>'.
   * @see org.xtext.exam22.dsl.Parenthesis
   * @generated
   */
  EClass getParenthesis();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.exam22.dsl.Parenthesis#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see org.xtext.exam22.dsl.Parenthesis#getExp()
   * @see #getParenthesis()
   * @generated
   */
  EReference getParenthesis_Exp();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DslFactory getDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.ModelImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__NAME = eINSTANCE.getModel_Name();

    /**
     * The meta object literal for the '<em><b>Functions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__FUNCTIONS = eINSTANCE.getModel_Functions();

    /**
     * The meta object literal for the '<em><b>Scenarios</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__SCENARIOS = eINSTANCE.getModel_Scenarios();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.FunctionImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__TYPES = eINSTANCE.getFunction_Types();

    /**
     * The meta object literal for the '<em><b>Return Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__RETURN_TYPE = eINSTANCE.getFunction_ReturnType();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.ScenarioImpl <em>Scenario</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.ScenarioImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getScenario()
     * @generated
     */
    EClass SCENARIO = eINSTANCE.getScenario();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENARIO__PARAMETERS = eINSTANCE.getScenario_Parameters();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENARIO__VARIABLES = eINSTANCE.getScenario_Variables();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENARIO__STATEMENTS = eINSTANCE.getScenario_Statements();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.StatementImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__EXPRESSION = eINSTANCE.getStatement_Expression();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.VariableDefImpl <em>Variable Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.VariableDefImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getVariableDef()
     * @generated
     */
    EClass VARIABLE_DEF = eINSTANCE.getVariableDef();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DEF__TYPE = eINSTANCE.getVariableDef_Type();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.AnnounceImpl <em>Announce</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.AnnounceImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getAnnounce()
     * @generated
     */
    EClass ANNOUNCE = eINSTANCE.getAnnounce();

    /**
     * The meta object literal for the '<em><b>Targets</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ANNOUNCE__TARGETS = eINSTANCE.getAnnounce_Targets();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.QuestionImpl <em>Question</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.QuestionImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getQuestion()
     * @generated
     */
    EClass QUESTION = eINSTANCE.getQuestion();

    /**
     * The meta object literal for the '<em><b>Output</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUESTION__OUTPUT = eINSTANCE.getQuestion_Output();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUESTION__VARIABLE = eINSTANCE.getQuestion_Variable();

    /**
     * The meta object literal for the '<em><b>Targets</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUESTION__TARGETS = eINSTANCE.getQuestion_Targets();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.EndImpl <em>End</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.EndImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getEnd()
     * @generated
     */
    EClass END = eINSTANCE.getEnd();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.TargetImpl <em>Target</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.TargetImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getTarget()
     * @generated
     */
    EClass TARGET = eINSTANCE.getTarget();

    /**
     * The meta object literal for the '<em><b>To</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TARGET__TO = eINSTANCE.getTarget_To();

    /**
     * The meta object literal for the '<em><b>Expressions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TARGET__EXPRESSIONS = eINSTANCE.getTarget_Expressions();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TARGET__CONDITION = eINSTANCE.getTarget_Condition();

    /**
     * The meta object literal for the '<em><b>Ending Targets</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TARGET__ENDING_TARGETS = eINSTANCE.getTarget_EndingTargets();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.EndingTargetImpl <em>Ending Target</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.EndingTargetImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getEndingTarget()
     * @generated
     */
    EClass ENDING_TARGET = eINSTANCE.getEndingTarget();

    /**
     * The meta object literal for the '<em><b>End</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENDING_TARGET__END = eINSTANCE.getEndingTarget_End();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENDING_TARGET__TARGET = eINSTANCE.getEndingTarget_Target();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.ParameterImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__TYPE = eINSTANCE.getParameter_Type();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.ExpImpl <em>Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.ExpImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getExp()
     * @generated
     */
    EClass EXP = eINSTANCE.getExp();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.CrossRefImpl <em>Cross Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.CrossRefImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getCrossRef()
     * @generated
     */
    EClass CROSS_REF = eINSTANCE.getCrossRef();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CROSS_REF__NAME = eINSTANCE.getCrossRef_Name();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.BooleanImpl <em>Boolean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.BooleanImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getBoolean()
     * @generated
     */
    EClass BOOLEAN = eINSTANCE.getBoolean();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOLEAN__LEFT = eINSTANCE.getBoolean_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN__OP = eINSTANCE.getBoolean_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOLEAN__RIGHT = eINSTANCE.getBoolean_Right();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.EqualImpl <em>Equal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.EqualImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getEqual()
     * @generated
     */
    EClass EQUAL = eINSTANCE.getEqual();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUAL__LEFT = eINSTANCE.getEqual_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EQUAL__OP = eINSTANCE.getEqual_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUAL__RIGHT = eINSTANCE.getEqual_Right();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.CompareImpl <em>Compare</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.CompareImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getCompare()
     * @generated
     */
    EClass COMPARE = eINSTANCE.getCompare();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARE__LEFT = eINSTANCE.getCompare_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARE__OP = eINSTANCE.getCompare_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARE__RIGHT = eINSTANCE.getCompare_Right();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.ConcatImpl <em>Concat</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.ConcatImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getConcat()
     * @generated
     */
    EClass CONCAT = eINSTANCE.getConcat();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONCAT__LEFT = eINSTANCE.getConcat_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONCAT__RIGHT = eINSTANCE.getConcat_Right();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.PlusMinusImpl <em>Plus Minus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.PlusMinusImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getPlusMinus()
     * @generated
     */
    EClass PLUS_MINUS = eINSTANCE.getPlusMinus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS_MINUS__LEFT = eINSTANCE.getPlusMinus_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLUS_MINUS__OP = eINSTANCE.getPlusMinus_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS_MINUS__RIGHT = eINSTANCE.getPlusMinus_Right();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.MultDivImpl <em>Mult Div</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.MultDivImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getMultDiv()
     * @generated
     */
    EClass MULT_DIV = eINSTANCE.getMultDiv();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULT_DIV__LEFT = eINSTANCE.getMultDiv_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULT_DIV__OP = eINSTANCE.getMultDiv_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULT_DIV__RIGHT = eINSTANCE.getMultDiv_Right();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.IntConstantImpl <em>Int Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.IntConstantImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getIntConstant()
     * @generated
     */
    EClass INT_CONSTANT = eINSTANCE.getIntConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_CONSTANT__VALUE = eINSTANCE.getIntConstant_Value();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.StringConstantImpl <em>String Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.StringConstantImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getStringConstant()
     * @generated
     */
    EClass STRING_CONSTANT = eINSTANCE.getStringConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_CONSTANT__VALUE = eINSTANCE.getStringConstant_Value();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.BoolConstantImpl <em>Bool Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.BoolConstantImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getBoolConstant()
     * @generated
     */
    EClass BOOL_CONSTANT = eINSTANCE.getBoolConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOL_CONSTANT__VALUE = eINSTANCE.getBoolConstant_Value();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.NotImpl <em>Not</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.NotImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getNot()
     * @generated
     */
    EClass NOT = eINSTANCE.getNot();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOT__EXP = eINSTANCE.getNot_Exp();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.TypeConstantImpl <em>Type Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.TypeConstantImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getTypeConstant()
     * @generated
     */
    EClass TYPE_CONSTANT = eINSTANCE.getTypeConstant();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_CONSTANT__TYPE = eINSTANCE.getTypeConstant_Type();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.ThisImpl <em>This</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.ThisImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getThis()
     * @generated
     */
    EClass THIS = eINSTANCE.getThis();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.VarRefImpl <em>Var Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.VarRefImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getVarRef()
     * @generated
     */
    EClass VAR_REF = eINSTANCE.getVarRef();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_REF__REF = eINSTANCE.getVarRef_Ref();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.FuncCallImpl <em>Func Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.FuncCallImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getFuncCall()
     * @generated
     */
    EClass FUNC_CALL = eINSTANCE.getFuncCall();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNC_CALL__REF = eINSTANCE.getFuncCall_Ref();

    /**
     * The meta object literal for the '<em><b>Expressions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNC_CALL__EXPRESSIONS = eINSTANCE.getFuncCall_Expressions();

    /**
     * The meta object literal for the '{@link org.xtext.exam22.dsl.impl.ParenthesisImpl <em>Parenthesis</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.exam22.dsl.impl.ParenthesisImpl
     * @see org.xtext.exam22.dsl.impl.DslPackageImpl#getParenthesis()
     * @generated
     */
    EClass PARENTHESIS = eINSTANCE.getParenthesis();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARENTHESIS__EXP = eINSTANCE.getParenthesis_Exp();

  }

} //DslPackage
