/**
 * generated by Xtext 2.29.0
 */
package org.xtext.exam22.dsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.exam22.dsl.Function#getTypes <em>Types</em>}</li>
 *   <li>{@link org.xtext.exam22.dsl.Function#getReturnType <em>Return Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.exam22.dsl.DslPackage#getFunction()
 * @model
 * @generated
 */
public interface Function extends CrossRef
{
  /**
   * Returns the value of the '<em><b>Types</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Types</em>' attribute list.
   * @see org.xtext.exam22.dsl.DslPackage#getFunction_Types()
   * @model unique="false"
   * @generated
   */
  EList<String> getTypes();

  /**
   * Returns the value of the '<em><b>Return Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Return Type</em>' attribute.
   * @see #setReturnType(String)
   * @see org.xtext.exam22.dsl.DslPackage#getFunction_ReturnType()
   * @model
   * @generated
   */
  String getReturnType();

  /**
   * Sets the value of the '{@link org.xtext.exam22.dsl.Function#getReturnType <em>Return Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Return Type</em>' attribute.
   * @see #getReturnType()
   * @generated
   */
  void setReturnType(String value);

} // Function
