/**
 * generated by Xtext 2.29.0
 */
package org.xtext.exam22.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>This</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.exam22.dsl.DslPackage#getThis()
 * @model
 * @generated
 */
public interface This extends Exp
{
} // This
