/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Require</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Require#getRequire <em>Require</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRequire()
 * @model
 * @generated
 */
public interface Require extends EObject
{
  /**
   * Returns the value of the '<em><b>Require</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Require</em>' containment reference.
   * @see #setRequire(EObject)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRequire_Require()
   * @model containment="true"
   * @generated
   */
  EObject getRequire();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Require#getRequire <em>Require</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Require</em>' containment reference.
   * @see #getRequire()
   * @generated
   */
  void setRequire(EObject value);

} // Require
