<File> ::= Package? Import* (Class|Interface|Enum)
<Package> ::= "package" <ID>('.'<ID>)* ';'
<Import> ::= "import" <ID>('.'<ID>)* ';'
<Class> ::= Modifier "class" <ID> ("extends" <ID>('.'<ID>)*)? ("implements" <ID>('.'<ID>)*)? '{' <Body>* '}'
<Modifier> ::= "public" | "protected" | "private" | "static"
<Body> ::= variable|constructor|method|class
<Variable> ::= Modifier* Type <ID> ('=' ... )?

<constructor> ::= ...
<method> ::= ...
<class> ::= ...
<Interface> ::= ...
<Enum> ::= ...
